export interface QuestionField {
  id: string;
  label: string;
  type: "select" | "text";
  placeholder?: string;
  options?: string[];
}

export const categoryQuestionnaires: Record<string, QuestionField[]> = {
  plumbing: [
    { id: "issue_type", label: "Type of plumbing work", type: "select", options: ["Leak repair", "New installation", "Blocked drain", "Boiler issue", "Bathroom fitting", "Radiator work", "Other"] },
    { id: "location_in_property", label: "Where in the property?", type: "select", options: ["Kitchen", "Bathroom", "Utility room", "En-suite", "Garden/exterior", "Multiple rooms", "Other"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "urgency_detail", label: "Is there active water damage or leaking?", type: "select", options: ["Yes — actively leaking", "Yes — but contained", "No — not urgent", "Not sure"] },
    { id: "access_info", label: "Are there any access issues? (e.g. loft, under floor)", type: "text", placeholder: "e.g. Pipe is under floorboards in upstairs bathroom" },
    { id: "existing_system", label: "Do you know your boiler/heating system type?", type: "text", placeholder: "e.g. Combi boiler, Worcester Bosch" },
    { id: "previous_work", label: "Has any previous repair been attempted?", type: "select", options: ["Yes", "No", "Not sure"] },
    { id: "materials", label: "Do you have materials or do you need the provider to supply them?", type: "select", options: ["I have materials", "Provider to supply", "Not sure yet"] },
    { id: "num_items", label: "How many items need work? (e.g. taps, radiators)", type: "text", placeholder: "e.g. 2 taps, 1 radiator" },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Parking available on drive, dog in property" },
  ],
  electrical: [
    { id: "work_type", label: "Type of electrical work", type: "select", options: ["Rewiring", "New sockets/switches", "Lighting installation", "Fuse board upgrade", "Testing/inspection", "Fault finding", "EV charger", "Other"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "num_rooms", label: "How many rooms are affected?", type: "select", options: ["1 room", "2-3 rooms", "4+ rooms", "Whole property", "External only"] },
    { id: "current_issue", label: "Is there a current fault or safety concern?", type: "select", options: ["Yes — no power", "Yes — tripping fuse", "Yes — sparking/burning smell", "No — planned work", "Not sure"] },
    { id: "fuse_board_age", label: "Approximate age of your fuse board", type: "select", options: ["Less than 5 years", "5-15 years", "15+ years", "Don't know"] },
    { id: "certificate_needed", label: "Do you need an electrical certificate (EICR)?", type: "select", options: ["Yes", "No", "Not sure"] },
    { id: "materials", label: "Do you have materials or do you need the provider to supply them?", type: "select", options: ["I have materials", "Provider to supply", "Not sure yet"] },
    { id: "access_info", label: "Any access considerations?", type: "text", placeholder: "e.g. Loft access needed, high ceilings" },
    { id: "existing_work", label: "Has any previous electrical work been done recently?", type: "text", placeholder: "e.g. Kitchen rewired last year" },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Listed building, alarm system installed" },
  ],
  carpentry: [
    { id: "work_type", label: "Type of carpentry work", type: "select", options: ["Door fitting/repair", "Shelving/storage", "Flooring", "Skirting boards", "Kitchen fitting", "Staircase", "Bespoke furniture", "Decking", "Other"] },
    { id: "material_type", label: "Preferred material", type: "select", options: ["Softwood", "Hardwood", "MDF/chipboard", "Plywood", "No preference", "Not sure"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "num_items", label: "How many items/areas need work?", type: "text", placeholder: "e.g. 3 doors, 2 sets of shelves" },
    { id: "measurements", label: "Do you have measurements?", type: "text", placeholder: "e.g. Door opening is 80cm x 200cm" },
    { id: "materials", label: "Do you have materials or need the provider to supply?", type: "select", options: ["I have materials", "Provider to supply", "Not sure yet"] },
    { id: "finish_required", label: "Is painting/finishing needed?", type: "select", options: ["Yes — painted", "Yes — varnished/stained", "No — bare wood", "Not sure"] },
    { id: "removal_needed", label: "Does old material need removing first?", type: "select", options: ["Yes", "No", "Not sure"] },
    { id: "access_info", label: "Any access considerations?", type: "text", placeholder: "e.g. Narrow hallway, upstairs room" },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Need to match existing style" },
  ],
  painting_decorating: [
    { id: "work_type", label: "Type of work", type: "select", options: ["Interior painting", "Exterior painting", "Wallpapering", "Feature wall", "Full room decoration", "Ceiling work", "Wood staining/varnishing", "Other"] },
    { id: "num_rooms", label: "How many rooms/areas?", type: "select", options: ["1 room", "2-3 rooms", "4-5 rooms", "Whole house", "Exterior only"] },
    { id: "room_sizes", label: "Room size(s)", type: "select", options: ["Small (box room)", "Medium (standard bedroom)", "Large (living room/open plan)", "Mixed sizes", "Not sure"] },
    { id: "surface_condition", label: "Current surface condition", type: "select", options: ["Good — just needs repainting", "Minor cracks/holes", "Significant prep needed", "Wallpaper removal needed", "Damp/mould present", "Not sure"] },
    { id: "ceiling_height", label: "Ceiling height", type: "select", options: ["Standard (2.4m)", "High ceilings (3m+)", "Vaulted/sloped", "Not sure"] },
    { id: "paint_chosen", label: "Have you chosen paint/wallpaper?", type: "select", options: ["Yes — already purchased", "Yes — but not purchased", "No — need advice", "Not sure"] },
    { id: "materials", label: "Do you have materials or need the provider to supply?", type: "select", options: ["I have materials", "Provider to supply", "Not sure yet"] },
    { id: "furniture_moving", label: "Will furniture need moving?", type: "select", options: ["Yes — I'll move it", "Yes — need help moving", "No — rooms are clear"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Colour scheme ideas, time restrictions" },
  ],
  roofing: [
    { id: "work_type", label: "Type of roofing work", type: "select", options: ["Leak repair", "Full re-roof", "Ridge tiles", "Flat roof repair", "Guttering", "Fascia/soffit", "Chimney repair", "Skylight/velux", "Other"] },
    { id: "roof_type", label: "Roof type", type: "select", options: ["Pitched — slate", "Pitched — tile", "Flat roof — felt", "Flat roof — fibreglass", "Flat roof — EPDM", "Not sure"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "num_storeys", label: "Number of storeys", type: "select", options: ["1 (bungalow)", "2", "3+", "Not sure"] },
    { id: "current_issue", label: "Is there active water ingress?", type: "select", options: ["Yes — actively leaking", "Yes — damp patches", "No — preventative", "Not sure"] },
    { id: "roof_age", label: "Approximate roof age", type: "select", options: ["Less than 10 years", "10-25 years", "25+ years", "Don't know"] },
    { id: "scaffolding", label: "Will scaffolding be needed?", type: "select", options: ["Yes", "No", "Not sure"] },
    { id: "access_info", label: "Any access issues?", type: "text", placeholder: "e.g. Rear access only, conservation area" },
    { id: "insurance_claim", label: "Is this an insurance claim?", type: "select", options: ["Yes", "No", "Pending"] },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Recent storm damage, listed property" },
  ],
  landscaping: [
    { id: "work_type", label: "Type of landscaping work", type: "select", options: ["Garden design", "Paving/patios", "Fencing", "Turfing", "Planting", "Tree surgery", "Drainage", "Decking", "Artificial grass", "Other"] },
    { id: "garden_size", label: "Garden size", type: "select", options: ["Small (under 50 sqm)", "Medium (50-150 sqm)", "Large (150+ sqm)", "Not sure"] },
    { id: "current_condition", label: "Current condition of the area", type: "select", options: ["Bare/cleared", "Overgrown", "Existing garden — needs updating", "New build — no garden yet", "Other"] },
    { id: "design_ready", label: "Do you have a design or plan?", type: "select", options: ["Yes — professional design", "Yes — rough idea/sketch", "No — need advice", "Open to suggestions"] },
    { id: "materials", label: "Do you have materials or need the provider to supply?", type: "select", options: ["I have materials", "Provider to supply", "Not sure yet"] },
    { id: "waste_removal", label: "Will waste/green waste need removing?", type: "select", options: ["Yes — significant amount", "Yes — small amount", "No", "Not sure"] },
    { id: "access_info", label: "Garden access", type: "select", options: ["Side gate", "Through the house", "Rear lane/alley", "Open access", "Other"] },
    { id: "slope", label: "Is the ground level or sloped?", type: "select", options: ["Level", "Slight slope", "Steep slope", "Terraced", "Not sure"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Pets, children's play area needed, budget range" },
  ],
  plastering: [
    { id: "work_type", label: "Type of plastering work", type: "select", options: ["Skim coat", "Full re-plaster", "Patching/repair", "Coving/cornice", "Rendering (exterior)", "Dry lining", "Artex removal", "Other"] },
    { id: "num_rooms", label: "How many rooms/areas?", type: "select", options: ["1 room", "2-3 rooms", "4+ rooms", "Whole house", "Exterior only"] },
    { id: "room_sizes", label: "Room size(s)", type: "select", options: ["Small (box room)", "Medium (standard bedroom)", "Large (living room/open plan)", "Mixed sizes", "Not sure"] },
    { id: "surface_condition", label: "Current wall condition", type: "select", options: ["Bare brick/block", "Old plaster — crumbling", "Old plaster — minor damage", "Plasterboard — needs skimming", "Artex to remove", "Not sure"] },
    { id: "ceiling_included", label: "Do ceilings need plastering too?", type: "select", options: ["Yes", "No", "Not sure"] },
    { id: "damp_issues", label: "Any damp or moisture issues?", type: "select", options: ["Yes — active damp", "Yes — treated damp", "No", "Not sure"] },
    { id: "ceiling_height", label: "Ceiling height", type: "select", options: ["Standard (2.4m)", "High ceilings (3m+)", "Vaulted/sloped", "Not sure"] },
    { id: "waste_removal", label: "Does old plaster need removing?", type: "select", options: ["Yes", "No", "Not sure"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Room cleared, dust sheets needed" },
  ],
  tiling: [
    { id: "work_type", label: "Type of tiling work", type: "select", options: ["Floor tiling", "Wall tiling", "Splashback", "Full bathroom tiling", "Full kitchen tiling", "Outdoor tiling", "Repair/replacement", "Other"] },
    { id: "location", label: "Where is the tiling needed?", type: "select", options: ["Bathroom", "Kitchen", "Hallway", "Living area", "Conservatory", "External", "Multiple rooms", "Other"] },
    { id: "area_size", label: "Approximate area (sqm)", type: "text", placeholder: "e.g. 12 sqm or 3m x 4m" },
    { id: "tile_type", label: "Tile type", type: "select", options: ["Ceramic", "Porcelain", "Natural stone", "Mosaic", "Large format (60cm+)", "Not chosen yet", "Not sure"] },
    { id: "tiles_purchased", label: "Have you purchased the tiles?", type: "select", options: ["Yes", "No — need help choosing", "No — but I know what I want"] },
    { id: "surface_prep", label: "Does the surface need preparation?", type: "select", options: ["Yes — old tiles to remove", "Yes — walls need boarding", "Yes — floor needs levelling", "No — ready to tile", "Not sure"] },
    { id: "underfloor_heating", label: "Is underfloor heating being installed?", type: "select", options: ["Yes — already installed", "Yes — needs installing too", "No", "Not sure"] },
    { id: "materials", label: "Do you have adhesive/grout or need the provider to supply?", type: "select", options: ["I have everything", "Provider to supply", "Not sure yet"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Pattern preferences, grout colour" },
  ],
  gas_heating: [
    { id: "work_type", label: "Type of gas/heating work", type: "select", options: ["Boiler service", "Boiler repair", "Boiler replacement", "New central heating", "Radiator install/replace", "Gas safety check", "Underfloor heating", "Smart thermostat", "Other"] },
    { id: "boiler_type", label: "Current boiler type", type: "select", options: ["Combi boiler", "System boiler", "Conventional/regular", "Back boiler", "No boiler", "Don't know"] },
    { id: "boiler_age", label: "Boiler age", type: "select", options: ["Less than 5 years", "5-10 years", "10-15 years", "15+ years", "Don't know"] },
    { id: "boiler_brand", label: "Boiler make/model (if known)", type: "text", placeholder: "e.g. Worcester Bosch Greenstar 30i" },
    { id: "num_radiators", label: "Number of radiators", type: "select", options: ["1-5", "6-10", "11-15", "15+", "Don't know"] },
    { id: "current_issue", label: "Is there a current fault?", type: "select", options: ["Yes — no heating", "Yes — no hot water", "Yes — both", "Yes — error code showing", "No — routine service", "Not sure"] },
    { id: "gas_safe_cert", label: "Do you need a gas safety certificate?", type: "select", options: ["Yes", "No", "Not sure"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "landlord_tenant", label: "Are you the homeowner or tenant?", type: "select", options: ["Homeowner", "Tenant", "Landlord", "Other"] },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Error codes, warranty status" },
  ],
  locksmith: [
    { id: "work_type", label: "Type of locksmith work", type: "select", options: ["Lock change", "Lock repair", "Lockout/emergency entry", "New lock installation", "Security upgrade", "UPVC mechanism", "Safe opening", "Other"] },
    { id: "lock_type", label: "Type of lock/door", type: "select", options: ["Yale (nightlatch)", "Mortice deadlock", "UPVC multi-point", "Composite door", "Patio/sliding door", "Padlock/shutter", "Not sure"] },
    { id: "num_locks", label: "How many locks need work?", type: "text", placeholder: "e.g. 2 locks" },
    { id: "urgency", label: "How urgent is this?", type: "select", options: ["Emergency — locked out now", "Today", "Within a few days", "Planned/no rush"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Commercial", "Other"] },
    { id: "insurance_required", label: "Do you need British Standard locks (for insurance)?", type: "select", options: ["Yes", "No", "Not sure"] },
    { id: "key_copies", label: "How many keys do you need?", type: "text", placeholder: "e.g. 3 keys" },
    { id: "security_assessment", label: "Would you like a security assessment?", type: "select", options: ["Yes", "No", "Maybe"] },
    { id: "proof_of_residence", label: "Can you provide proof of address?", type: "select", options: ["Yes", "Not currently available"] },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Snap-proof locks preferred, communal entrance" },
  ],
  cleaning: [
    { id: "work_type", label: "Type of cleaning", type: "select", options: ["One-off deep clean", "Regular cleaning", "End of tenancy", "After builders clean", "Carpet cleaning", "Oven cleaning", "Window cleaning", "Commercial clean", "Other"] },
    { id: "property_size", label: "Property size", type: "select", options: ["Studio/1 bed", "2 bed", "3 bed", "4+ bed", "Commercial/office", "Other"] },
    { id: "num_bathrooms", label: "Number of bathrooms", type: "select", options: ["1", "2", "3+", "N/A"] },
    { id: "current_condition", label: "Current condition", type: "select", options: ["Generally tidy", "Needs a good clean", "Heavily soiled/neglected", "Post-construction mess", "Not sure"] },
    { id: "cleaning_products", label: "Do you provide cleaning products?", type: "select", options: ["Yes", "No — provider to supply", "No preference"] },
    { id: "frequency", label: "How often do you need cleaning?", type: "select", options: ["One-off", "Weekly", "Fortnightly", "Monthly", "Other"] },
    { id: "pets", label: "Are there pets in the property?", type: "select", options: ["Yes — cats", "Yes — dogs", "Yes — other", "No pets"] },
    { id: "access_method", label: "How will the cleaner access the property?", type: "select", options: ["I'll be home", "Key safe", "Key with neighbour", "To be arranged"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Focus areas, allergies, time preferences" },
  ],
  general_maintenance: [
    { id: "work_type", label: "Type of maintenance work", type: "select", options: ["Furniture assembly", "Shelving/hanging", "Door adjustment", "General repairs", "Gutter clearing", "Pressure washing", "Fence repair", "Odd jobs", "Other"] },
    { id: "num_tasks", label: "How many tasks/jobs?", type: "select", options: ["1 small task", "2-3 tasks", "4+ tasks", "Full day of odd jobs"] },
    { id: "estimated_time", label: "How long do you think the work will take?", type: "select", options: ["Less than 1 hour", "1-2 hours", "Half day", "Full day", "Not sure"] },
    { id: "tools_needed", label: "Are any specialist tools needed?", type: "select", options: ["No — basic tools", "Yes", "Not sure"] },
    { id: "materials", label: "Do you have materials or need the provider to supply?", type: "select", options: ["I have materials", "Provider to supply", "Not sure yet"] },
    { id: "height_work", label: "Is there any work at height?", type: "select", options: ["Yes — ladder needed", "Yes — scaffolding needed", "No", "Not sure"] },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "access_info", label: "Any access or parking information?", type: "text", placeholder: "e.g. Permit parking area, tools through rear" },
    { id: "description_detail", label: "Please describe the tasks in more detail", type: "text", placeholder: "e.g. Hang 3 pictures, fix wobbly bannister, assemble wardrobe" },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Elderly occupant, time restrictions" },
  ],
  other: [
    { id: "work_description", label: "What type of work do you need?", type: "text", placeholder: "Describe the trade or skill needed" },
    { id: "property_type", label: "Property type", type: "select", options: ["Detached house", "Semi-detached", "Terraced", "Flat/apartment", "Bungalow", "Commercial", "Other"] },
    { id: "scope", label: "Scope of work", type: "select", options: ["Small repair", "Medium project", "Large project", "Ongoing work", "Not sure"] },
    { id: "materials", label: "Do you have materials or need the provider to supply?", type: "select", options: ["I have materials", "Provider to supply", "Not sure yet"] },
    { id: "access_info", label: "Any access or parking information?", type: "text", placeholder: "e.g. Permit parking, rear access only" },
    { id: "estimated_time", label: "How long do you think the work will take?", type: "select", options: ["Less than 1 hour", "1-2 hours", "Half day", "Full day", "Multiple days", "Not sure"] },
    { id: "previous_attempts", label: "Has any previous work been done?", type: "text", placeholder: "e.g. Attempted DIY repair" },
    { id: "extra_info", label: "Anything else the provider should know?", type: "text", placeholder: "e.g. Specific requirements, preferences" },
  ],
};
